# Generated by Django 4.2.13 on 2024-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('pais_origen', models.CharField(max_length=50)),
                ('id_ocio', models.IntegerField()),
            ],
            options={
                'db_table': 'cocina',
            },
        ),
        migrations.CreateModel(
            name='Ocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ocio',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField()),
                ('id_ocio', models.IntegerField()),
            ],
            options={
                'db_table': 'serie',
            },
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField()),
                ('id_ocio', models.IntegerField()),
            ],
            options={
                'db_table': 'videojuego',
            },
        ),
    ]
